name: 'rust-grcov'
description: 'Collect and aggregate code coverage information with the Mozilla grcov tool'
author: 'actions-rs team'
branding:
  icon: play-circle
  color: black
inputs:
  args:
    description: Arguments for the grcov command
    required: false

outputs:
  report:
    description: Absolute path to the generated code coverage file

runs:
  using: 'node12'
  main: 'dist/index.js'
